name: Java CI with Gradle

on:
  push:
    branches:
      - '*'
  schedule:
    - cron: '1 6 * * SUN'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
    - name: Post coverage to Slack
      shell: bash
      env:
        SLACK_URL: ${{ secrets.SLACK_URL }}
      run: |
        ./post-coverage-to-slack.sh "$SLACK_URL"
